# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 10:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='owner',
            name='balance',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
