# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20160905_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
