# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_recharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Only 10 digits allowed.", regex='^\\+?1?\\d{10}$')]),
        ),
    ]
