# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 06:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20160908_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debit',
            name='balance',
        ),
        migrations.AddField(
            model_name='debit',
            name='cvv',
            field=models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debit',
            name='dbalance',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='debit',
            name='expiration',
            field=models.IntegerField(choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2024, '2024'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=1),
            preserve_default=False,
        ),
    ]
