# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_auto_20160909_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recharge',
            options={'ordering': ['timestamp']},
        ),
    ]
