# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 09:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import wallet.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_auto_20160909_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Numeric Field. Only 10 digits allowed.', regex='^\\+?1?\\d{10}$')])),
                ('transferamount', models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(5000)])),
            ],
            bases=(models.Model, wallet.models.Main),
        ),
    ]
