# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='transferamount',
            new_name='transfer_amount',
        ),
    ]
