# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_auto_20160910_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='transfer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 10, 10, 1, 13, 766255, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
