# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_transfer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='balance',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
