# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 13:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_auto_20160910_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='from_number',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator(message='Numeric Field. Only 10 digits allowed.', regex='^\\+?1?\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='received_amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 11, 13, 43, 5, 374324, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
