# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_auto_20160911_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='received_amount',
        ),
    ]
