# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_remove_owner_received_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='full_name',
        ),
    ]
