# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0028_receiver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receiver',
            new_name='ReceivedAmount',
        ),
    ]
