# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0029_auto_20160912_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedamount',
            old_name='received_amount',
            new_name='rec_amount',
        ),
    ]
