# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0030_auto_20160912_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedamount',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='receivedamount',
            name='rec_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedamount',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 12, 12, 52, 58, 326962, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
