# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0031_auto_20160912_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedamount',
            name='rec_number',
        ),
        migrations.AddField(
            model_name='receivedamount',
            name='rec_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
