# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 19:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0032_auto_20160912_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedamount',
            name='rec_amount',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
