# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0033_auto_20160913_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='from_number',
        ),
    ]
