# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0037_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='uniquepin',
            new_name='verification_code',
        ),
    ]
