# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 13:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0040_codereceived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_amount',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(10)]),
        ),
    ]
